name:                todo-app
version:             0.1.0.0
github:              "githubuser/todo-app"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/todo-app#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- wai
- warp
- persistent
- persistent-postgresql
- persistent-template
- servant
- servant-server
- text
- monad-logger
- resourcet
- blaze-html
- blaze-markup
- servant-blaze
- http-api-data
- dotenv
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  todo-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - todo-app

tests:
  todo-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - todo-app
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
